# Add 'repo' label to any non-docs file changes
repo:
- '*'
- _plugins/**/*
- .github/**/*
# if the changes happen in the 'docs' directory
docs:
- docs/**/*
# if changes happen to workflows
workflow;
- .github/workflows/*
# if changes are api related
API:
- docs/api/*