remote_theme: just-the-docs/just-the-docs
color_scheme: dark
markdown: GFM
defaults:
  - scope:
      permalink: /content/en/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "404.md", 405.md]
