markdown: GFM
defaults:
  - scope:
      path: "content/en"
    values:
      layout: "pages"
      permalink: /users
      permalink: /maps
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "404.md"]
