remote_theme: just-the-docs/just-the-docs
color_scheme: dark  
markdown: GFM

#defaults:
 # - scope:
     # permalink: /content/en/:title/
logo: /assets/images/ppypedialogo.png
feed_items: 90
feed_update_period: daily
feed_update_frequency: 2
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "404.md", "/templates/*", templates/*, osu!mania.md, non-existant, docs/content/en/modes/osu!/osu!.md!]
ga_tracking: G-737VMDEJJQ
ga_tracking_anonymize_ip: true
plugins:
  - jekyll-seo-tag
  - jekyll-asciidoc
  - jekyll-toc
  - jekyll-wiki
  - jekyll-mediawiki
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
feed_items: 90
feed_update_period: daily
feed_update_frequency: 2
collections:
categories: user, content, events, users, maps
output: true
paginate: 5
site_root: ./docs
footer_content: peppypedia, started by Windows Me (windowsmeosu on github) documents top osu! players, in-game features, etc. peppypedia is not a replacement for the osu!wiki. Copyright, MiloTilo Services, BV.
copyright: MiloTilo Services
gh_edit_link: true
gh_edit_link_text: "Edit or add improvisations to this page on GitHub."
gh_edit_repository: "https://github.com/windowsmeosu/peppypedia"
gh_edit_branch: "70-peppypedia-todo-checklist"
gh_edit_view_mode: "edit" 
gh_edit_source: docs