markdown: GFM
defaults:
  - scope:
      path: "content/en"
    values:
      layout: "users", "maps"
      permalink: /wiki/:title
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "404.md"]
