baseURL: 'https://windowsmeosu.github.io/peppypedia'
paginate: 200
defaultContentLanguage: en
enableEmoji: true
timeZone: Amsterdam
footnotereturnlinkcontents: ↩
languageCode: en-nl
title: peppypedia
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken
  - detect-package-manager
googleAnalytics: false
pluralizeListTitles: false
disableAliases: true
minify:
  tdewolff:
    css: {}
    html:
      keepWhitespace: true
module:
  hugoVersion:
    min: 0.56.0
  imports:
    - path: github.com/gohugoio/gohugoioTheme
outputs:
  home:
    - HTML
    - RSS
    - REDIR
    - HEADERS
  section:
    - HTML
    - RSS
mediaTypes:
  text/netlify:
    delimiter: ''
outputFormats:
  REDIR:
    mediatype: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediatype: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: date
      weight: 10
      pattern: '2006'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
# we'll keep this up cuz why not
