name: catschema

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: curl
        run: curl https://milotilo.ddns.net/peppypediadata/page_schema.xsd

      - name: wget
        run: |
         choco install wget
         wget https://milotilo.ddns.net/peppypediadata/page_schema.xsd
         
