name: catschema

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: curl
        run: curl https://milotilo.ddns.net/peppypediadata/page_schema.xsd

      - name: winget
        run: |
         winget https://milotilo.ddns.net/peppypediadata/page_schema.xsd
         
