name: cat

on:
  push:
    branches:
      - master
      - testing
      - testingv2

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: cat
    url: https://milotilo.ddns.net/peppypediadata/page_schema.xsd
    steps:
     -  name: checking schema
     -  run: echo checking schema
      # var cat = require('xsd'), dom = require('@xmldom/xmldom').DOMParser
      - name: deploy
