on:
  workflow_dispatch:
# irc

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy Chain
    steps:
    - name: Acknowledge
      id: acknowledge
      uses: Gottox/irc-message-action@v2
      with:
        channel: '##peppypedia'
        nickname: peppybot
        response_allow_from: MiloTilo
        # 5 hours:
        response_timeout: 18000
        message: |-
          ${{ github.actor }} pushed something: ${{ github.event.compare }}
          Please acknowledge with "ok"!
    # An Acknowledger can reply to this with "mynickname: ok"
    - name: Print Acknowledger
      run: echo "${{ steps.response.outputs.response_from }}"
    - name: Check Acknowledge
      run: test "${{ steps.response.outputs.response }}" = ok
    - name: Deploy
      run: ./deploy.sh
      
      
    
