name: peppypedia-submodule-check
on:

  push:
    branches: ["master"]


  workflow_dispatch:

permissions:
  contents: read
 # pages: write
  id-token: write
  jobs:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@master
       with:
          submodules: true
